music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'
urlpatterns = [
    
    url(r'^$', views.index, name='index'),
    url(r'^detail/', views.detail, name='detail'),
]

mysite101/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("music.urls")),
]

music/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

music/views.py
from django.shortcuts import render
from django.http import HttpResponse 

def index(request):
   return render(request, "music/index.html", locals())

def detail(request):
   return render(request, "music/detail.html", locals())

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap Cheat Sheet</title>
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'music/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>
    <style>
	   .navbar{
	      margin-bottom:0;
		  border-radius:0;
	   }
	</style>
  </head>
  <body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'music:detail' %}">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<ul>

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap Cheat Sheet</title>
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'music/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>
    <style>
	   .navbar{
	      margin-bottom:0;
		  border-radius:0;
	   }
	</style>
  </head>
  <body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'music:index' %}">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="jumbotron text-center">
     <div class="container">
	    <h1>Welcome To My Website</h1>
		<p>this is the test but i'm not sure that we are all okay!</p>
		<a href="#" class="btn btn-primary">Read More</a>
     </div>
	 
  </div>
  
  
	<div class="container">
		<h1 class="page-header">Bootstrap Example <small>Secondary text</small></h1>
		<p class="lead">That is, if at all possible, make the variable local. Making it a class 
		member should be a last resort, not the default.</p> 
		<p><mark>Why should local be preferred memory</mark> footprint of your objects increase the. 
		over a class data member? For the same reason that local variables are preferred 
		over global variables. <del>Local variables are easier</del> to understand. They only exist 
		in the block they are defined in and can only directly influence code in this block. 
		Data members exist for <u>the entire lifetime of the object</u> they are part of. Determining 
		if they are initialized correctly and their effect requires one to look at every method 
		of the class. In a multi-threaded environment, synchronization of access to data members 
		is another complication that local variables do not have. Data members also.</p> 
	<hr>
	
	<p class="text-left">Left aligned text.</p>
	<p class="text-center">Center aligned text.</p>
	<p class="text-right">Right aligned text.</p>
	<p class="text-justify">Justified text.</p>
	<p class="text-nowrap">No wrap text.</p> 
	
	<div class="pull-right">Div floated to right</div>
	<div class="pull-left">Div floated to left</div>
	
	<div class="clearfix"></div>
	<hr>
	
	<blockquote class="blockquote-reverse">
		<p>For the same reason that local variables are preferred over global variables.</p>
		 <footer>Quote by <cite title="John Doe">John Doe</cite></footer>
	</blockquote>
	
	<ul class="list-unstyled">
		<li>Item One</li>
		<li>Item Two</li>
		<li>Item Three</li>
		<li>Item Four</li>
	</ul>
	
	<ul class="list-inline">
		<li>Item One</li>
		<li>Item Two</li>
		<li>Item Three</li>
		<li>Item Four</li>
	</ul>
	
	<hr>
	
	<code>&lt;h1&gt;Heading Text&lt;/h1&gt;</code>
	<br>
	Change directory with  <kbd>cd</kbd>
	<br>
	To edit settings, press  <kbd><kbd>ctrl</kbd> + </kbd>, </kbd></kbd>
	
	<hr>
	
	<p class="text-primary">Hello World</p>
	<p class="text-success">Hello World</p>
	<p class="text-info">Hello World</p>
	<p class="text-warning">Hello World</p>
	<p class="text-danger">Hello World</p>
	<p class="text-muted">Hello World</p>
	
	<p class="bg-primary">Hello World</p>
	<p class="bg-success">Hello World</p>
	<p class="bg-info">Hello World</p>
	<p class="bg-warning">Hello World</p>
	<p class="bg-danger">Hello World</p>
	<p class="bg-muted">Hello World</p>
	
	</div>
	
	<div class="container">
		<button class="btn btn-default">Button</button>
		<a href="#" class="btn btn-default" role="button">Link</a>
		<input type="submit" class="btn btn-default btn-xs" value="Submit">
		<br>
		<button class="btn btn-default">Default</button>
		<button class="btn btn-primary">Primary</button>
		<button class="btn btn-success">Success</button>
		<button class="btn btn-info">Info</button>
		<button class="btn btn-warning">Warning</button>
		<button class="btn btn-danger">Delete</button>
		<button class="btn btn-link">Link</button>
		<br>
		<button class="btn btn-default btn-lg">Default</button>
		<button class="btn btn-default">Default</button>
		<button class="btn btn-primary btn-sm">Default</button>
		<button class="btn btn-default btn-xs" disabled="disabled">Default</button>
	
	</div>
	
	<hr>
	
	<div class="container">
	  <form>
	    <div class="form-group">
		  <label>Name</label>
		  <input type="text" class="form-control" placeholder="Add Name">
		</div>
		<div class="form-group">
		  <label>email</label>
		  <input type="text" class="form-control" placeholder="Add Email">
		</div>
		<div class="form-group">
		  <label>Message</label>
		  <textarea class="form-control" placeholder="Add Message"></textarea>
		</div>
		<div class="form-group">
		  <label>Gender</label>
		    <select class="form-control">
			  <option value="male">Male</option>
			  <option value="female">Female</option>
			  <option value="other">Other</option>
			</select>
		</div>
		
		<div class="form-group">
		  <label>Upload File</label>
		  <input type="file">
		  <p class="help-block">Only png and jpg allowed</p>
		</div>
		
		<div class="checkbox">
		  <label>
		    <input type="checkbox">Check me out
		  </label>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	  </form>
	  
	  <hr>
	  
	  <form class="form-inline">
	    
		<div class="form-group">
		  <label>Email</label>
		  <input type="email" class="form-control" placeholder="Email">
		</div>
		<div class="form-group">
		  <label>Password</label>
		  <input type="password" class="form-control" placeholder="Password">
		</div>
		
		
		<div class="checkbox">
		  <label>
		    <input type="checkbox">  Remember me
		  </label>
		</div>
		<button type="submit" class="btn btn-default">Login</button>
	  </form>
	 </container>
	 
	 <hr>
	 
	<div class="container">
	   <table class="table table-striped table-bordered table-hover table-condensed">
	     <tr>
		    <th>Firstname</th>
			<th>Lastname</th>
			<th>Age</th>
		</tr>
		<tr class="danger">
		    <th>Jill</th>
			<th>smith</th>
			<th>59</th>
		</tr>
		<tr>
		    <th>Eve</th>
			<th>Jackson</th>
			<th>24</th>
		</tr>
		<tr class="success">
		    <th>John</th>
			<th>Doe</th>
			<th>34</th>
		</tr>
		<tr>
		    <th>Peter</th>
			<th>Jane</th>
			<th>44</th>
		</tr>
		<tr>
		    <th>Danny</th>
			<th>Chung</th>
			<th>37</th>
		</tr>
	   </table>
	</div>
	
	<hr>
	
	<div class="container">
	  <ul class="list-group">
		<li class="list-group-item">Item One</li>
		<li class="list-group-item">Item Two</li>
		<li class="list-group-item">Item Three</li>
		<li class="list-group-item">Item Four</li>
	  </ul>
	  
	  <div class="list-group">
   	    <a href="http://www.google.com" class="list-group-item active">Item One</a>
		<a href="#" class="list-group-item ">Item Two</a>
		<a href="#" class="list-group-item list-group-item-success">Item Three</a>
		<a href="#" class="list-group-item ">Item Four</a>
	  </div>
	  
	  <div class="container">
	    <div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">Panel title</h3>
		  </div>
		  <div class="panel-body">
		    Panel content
	      </div>
		  <div class="panel-footer">Panel Footer</div>
	    </div>
	  </div>
	   
	  <div class="well">Hello world</div>
	  <div class="well well-lg">Hello world</div>
	  <div class="well well-sm">Hello world</div>
	  
	  <hr>
	  
	  <div class="alert alert-success" role="alert">A success alert</div>
	  <div class="alert alert-info" role="alert">An info alert</div>
	  <div class="alert alert-warning" role="alert">A warning alert</div>
	  <div class="alert alert-danger" role="alert">A danger alert</div>
	  
	  <div class="alert alert-warning alert-dismissible" role="alert">
	    <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		You can close this alert
	  </div>
	  
	  <div class="progress">
	    <div class="progress-bar progress-bar-success progress-bar-striped active" style="width:70%;">
		  70%
		</div>
	  </div>
	  
	  <hr>
	  
	  <span class="label label-default">Default</span>
	  <h1>hello <span class="label label-primary">Primary</span></h1>
	  <span class="label label-success">Success</span>
	  <span class="label label-info"> Info</span>
	  <span class="label label-warning">Warning</span>
	  <span class="label label-danger">Danger</span>
	  
	  
	  <a href="#">Inbox <span class="badge">50</span></a>
	  
	  <button class="btn btn-primary" type="button">
	     Messages <span class="badge">2</span>
	  </button>
	
	</div>
	<div style="height: 400px"></div>
    
  </body>
</html>

music/templates/music/index.html
{% include 'music/base.html' %}

<h1>Display the indexView here</h1>